### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by dalmatele** [uizaio/uiza-sdk-player-ios#1]
I used Version 10.2 (10E125)
 I added UizaSDK8 and UizaSDK by cocoapod.
When I imported UizaSDK/UizaSDK8 to my project I've got this error:
"Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler."
What do I do now?

**Comment by kennic** [comment]
Please run `pod update` to get the lastest version `7.0.6` for Swift 5 project
